>>>>>>>CREATE A .conf FILE AT THE LOCATION<<<<<<<<<<<<
sudo vim /etc/nginx/sites-available/reverse-proxy.conf


>>>>>>>>ADD THIS CONTENT (THIS IS FOR HTTPS)<<<<<<<<<

server {
    listen 80;
    server_name mydomain.com;

    # Redirect all HTTP to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name mydomain.com;

    ssl_certificate     /etc/nginx/ssl/mycert.crt;
    ssl_certificate_key /etc/nginx/ssl/mykey.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # Serve frontend
    root /var/www/frontend;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # Reverse proxy for backend API
    location /api/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

>>>>>>ENABLE THE SITE<<<<<<<<<

sudo ln -s /etc/nginx/sites-available/myapp.conf /etc/nginx/sites-enabled/

>>>>>>>TEST AND RELOAD<<<<<<<

sudo nginx -t
sudo systemctl reload nginx

